// Code generated by protoc-gen-go. DO NOT EDIT.
// source: event-structs-generated.proto

/*
Package tracer is a generated protocol buffer package.

It is generated from these files:
	event-structs-generated.proto

It has these top-level messages:
	ProtobufCommonEvent
	ProtobufConnectV4Event
	ProtobufConnectV6Event
	ProtobufChmodEvent
	ProtobufChownEvent
	ProtobufCloseEvent
	ProtobufFchmodEvent
	ProtobufFchmodatEvent
	ProtobufFchownEvent
	ProtobufFchownatEvent
	ProtobufMkdirEvent
	ProtobufMkdiratEvent
	ProtobufOpenEvent
	ProtobufReadEvent
	ProtobufWriteEvent
	Empty
	Metric
*/
package tracer

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"

import (
	context "golang.org/x/net/context"
	grpc "google.golang.org/grpc"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type ProtobufCommonEvent struct {
	Timestamp uint64 `protobuf:"varint,1,opt,name=Timestamp,json=timestamp" json:"Timestamp,omitempty"`
	Pid       int64  `protobuf:"varint,2,opt,name=Pid,json=pid" json:"Pid,omitempty"`
	Ret       int64  `protobuf:"varint,3,opt,name=Ret,json=ret" json:"Ret,omitempty"`
	Name      string `protobuf:"bytes,4,opt,name=Name,json=name" json:"Name,omitempty"`
	Hash      uint64 `protobuf:"varint,5,opt,name=Hash,json=hash" json:"Hash,omitempty"`
}

func (m *ProtobufCommonEvent) Reset()                    { *m = ProtobufCommonEvent{} }
func (m *ProtobufCommonEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtobufCommonEvent) ProtoMessage()               {}
func (*ProtobufCommonEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{0} }

func (m *ProtobufCommonEvent) GetTimestamp() uint64 {
	if m != nil {
		return m.Timestamp
	}
	return 0
}

func (m *ProtobufCommonEvent) GetPid() int64 {
	if m != nil {
		return m.Pid
	}
	return 0
}

func (m *ProtobufCommonEvent) GetRet() int64 {
	if m != nil {
		return m.Ret
	}
	return 0
}

func (m *ProtobufCommonEvent) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *ProtobufCommonEvent) GetHash() uint64 {
	if m != nil {
		return m.Hash
	}
	return 0
}

type ProtobufConnectV4Event struct {
	Saddr uint32 `protobuf:"varint,1,opt,name=Saddr,json=saddr" json:"Saddr,omitempty"`
	Daddr uint32 `protobuf:"varint,2,opt,name=Daddr,json=daddr" json:"Daddr,omitempty"`
	Sport uint32 `protobuf:"varint,3,opt,name=Sport,json=sport" json:"Sport,omitempty"`
	Dport uint32 `protobuf:"varint,4,opt,name=Dport,json=dport" json:"Dport,omitempty"`
	Netns uint32 `protobuf:"varint,5,opt,name=Netns,json=netns" json:"Netns,omitempty"`
}

func (m *ProtobufConnectV4Event) Reset()                    { *m = ProtobufConnectV4Event{} }
func (m *ProtobufConnectV4Event) String() string            { return proto.CompactTextString(m) }
func (*ProtobufConnectV4Event) ProtoMessage()               {}
func (*ProtobufConnectV4Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{1} }

func (m *ProtobufConnectV4Event) GetSaddr() uint32 {
	if m != nil {
		return m.Saddr
	}
	return 0
}

func (m *ProtobufConnectV4Event) GetDaddr() uint32 {
	if m != nil {
		return m.Daddr
	}
	return 0
}

func (m *ProtobufConnectV4Event) GetSport() uint32 {
	if m != nil {
		return m.Sport
	}
	return 0
}

func (m *ProtobufConnectV4Event) GetDport() uint32 {
	if m != nil {
		return m.Dport
	}
	return 0
}

func (m *ProtobufConnectV4Event) GetNetns() uint32 {
	if m != nil {
		return m.Netns
	}
	return 0
}

type ProtobufConnectV6Event struct {
	Saddr string `protobuf:"bytes,1,opt,name=Saddr,json=saddr" json:"Saddr,omitempty"`
	Daddr string `protobuf:"bytes,2,opt,name=Daddr,json=daddr" json:"Daddr,omitempty"`
	Sport uint32 `protobuf:"varint,3,opt,name=Sport,json=sport" json:"Sport,omitempty"`
	Dport uint32 `protobuf:"varint,4,opt,name=Dport,json=dport" json:"Dport,omitempty"`
	Netns uint32 `protobuf:"varint,5,opt,name=Netns,json=netns" json:"Netns,omitempty"`
}

func (m *ProtobufConnectV6Event) Reset()                    { *m = ProtobufConnectV6Event{} }
func (m *ProtobufConnectV6Event) String() string            { return proto.CompactTextString(m) }
func (*ProtobufConnectV6Event) ProtoMessage()               {}
func (*ProtobufConnectV6Event) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{2} }

func (m *ProtobufConnectV6Event) GetSaddr() string {
	if m != nil {
		return m.Saddr
	}
	return ""
}

func (m *ProtobufConnectV6Event) GetDaddr() string {
	if m != nil {
		return m.Daddr
	}
	return ""
}

func (m *ProtobufConnectV6Event) GetSport() uint32 {
	if m != nil {
		return m.Sport
	}
	return 0
}

func (m *ProtobufConnectV6Event) GetDport() uint32 {
	if m != nil {
		return m.Dport
	}
	return 0
}

func (m *ProtobufConnectV6Event) GetNetns() uint32 {
	if m != nil {
		return m.Netns
	}
	return 0
}

type ProtobufChmodEvent struct {
	Filename []byte `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Mode     uint64 `protobuf:"varint,2,opt,name=mode" json:"mode,omitempty"`
}

func (m *ProtobufChmodEvent) Reset()                    { *m = ProtobufChmodEvent{} }
func (m *ProtobufChmodEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtobufChmodEvent) ProtoMessage()               {}
func (*ProtobufChmodEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{3} }

func (m *ProtobufChmodEvent) GetFilename() []byte {
	if m != nil {
		return m.Filename
	}
	return nil
}

func (m *ProtobufChmodEvent) GetMode() uint64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type ProtobufChownEvent struct {
	Filename []byte `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	User     uint32 `protobuf:"varint,2,opt,name=user" json:"user,omitempty"`
	Group    uint32 `protobuf:"varint,3,opt,name=group" json:"group,omitempty"`
}

func (m *ProtobufChownEvent) Reset()                    { *m = ProtobufChownEvent{} }
func (m *ProtobufChownEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtobufChownEvent) ProtoMessage()               {}
func (*ProtobufChownEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{4} }

func (m *ProtobufChownEvent) GetFilename() []byte {
	if m != nil {
		return m.Filename
	}
	return nil
}

func (m *ProtobufChownEvent) GetUser() uint32 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *ProtobufChownEvent) GetGroup() uint32 {
	if m != nil {
		return m.Group
	}
	return 0
}

type ProtobufCloseEvent struct {
	Fd uint64 `protobuf:"varint,1,opt,name=fd" json:"fd,omitempty"`
}

func (m *ProtobufCloseEvent) Reset()                    { *m = ProtobufCloseEvent{} }
func (m *ProtobufCloseEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtobufCloseEvent) ProtoMessage()               {}
func (*ProtobufCloseEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{5} }

func (m *ProtobufCloseEvent) GetFd() uint64 {
	if m != nil {
		return m.Fd
	}
	return 0
}

type ProtobufFchmodEvent struct {
	Fd   uint64 `protobuf:"varint,1,opt,name=fd" json:"fd,omitempty"`
	Mode uint64 `protobuf:"varint,2,opt,name=mode" json:"mode,omitempty"`
}

func (m *ProtobufFchmodEvent) Reset()                    { *m = ProtobufFchmodEvent{} }
func (m *ProtobufFchmodEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtobufFchmodEvent) ProtoMessage()               {}
func (*ProtobufFchmodEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{6} }

func (m *ProtobufFchmodEvent) GetFd() uint64 {
	if m != nil {
		return m.Fd
	}
	return 0
}

func (m *ProtobufFchmodEvent) GetMode() uint64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type ProtobufFchmodatEvent struct {
	Dfd      int64  `protobuf:"varint,1,opt,name=dfd" json:"dfd,omitempty"`
	Filename []byte `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	Mode     uint64 `protobuf:"varint,3,opt,name=mode" json:"mode,omitempty"`
}

func (m *ProtobufFchmodatEvent) Reset()                    { *m = ProtobufFchmodatEvent{} }
func (m *ProtobufFchmodatEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtobufFchmodatEvent) ProtoMessage()               {}
func (*ProtobufFchmodatEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{7} }

func (m *ProtobufFchmodatEvent) GetDfd() int64 {
	if m != nil {
		return m.Dfd
	}
	return 0
}

func (m *ProtobufFchmodatEvent) GetFilename() []byte {
	if m != nil {
		return m.Filename
	}
	return nil
}

func (m *ProtobufFchmodatEvent) GetMode() uint64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type ProtobufFchownEvent struct {
	Fd    uint64 `protobuf:"varint,1,opt,name=fd" json:"fd,omitempty"`
	User  uint32 `protobuf:"varint,2,opt,name=user" json:"user,omitempty"`
	Group uint32 `protobuf:"varint,3,opt,name=group" json:"group,omitempty"`
}

func (m *ProtobufFchownEvent) Reset()                    { *m = ProtobufFchownEvent{} }
func (m *ProtobufFchownEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtobufFchownEvent) ProtoMessage()               {}
func (*ProtobufFchownEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{8} }

func (m *ProtobufFchownEvent) GetFd() uint64 {
	if m != nil {
		return m.Fd
	}
	return 0
}

func (m *ProtobufFchownEvent) GetUser() uint32 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *ProtobufFchownEvent) GetGroup() uint32 {
	if m != nil {
		return m.Group
	}
	return 0
}

type ProtobufFchownatEvent struct {
	Dfd      int64  `protobuf:"varint,1,opt,name=dfd" json:"dfd,omitempty"`
	Filename []byte `protobuf:"bytes,2,opt,name=filename,proto3" json:"filename,omitempty"`
	User     uint32 `protobuf:"varint,3,opt,name=user" json:"user,omitempty"`
	Group    uint32 `protobuf:"varint,4,opt,name=group" json:"group,omitempty"`
	Flag     int64  `protobuf:"varint,5,opt,name=flag" json:"flag,omitempty"`
}

func (m *ProtobufFchownatEvent) Reset()                    { *m = ProtobufFchownatEvent{} }
func (m *ProtobufFchownatEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtobufFchownatEvent) ProtoMessage()               {}
func (*ProtobufFchownatEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{9} }

func (m *ProtobufFchownatEvent) GetDfd() int64 {
	if m != nil {
		return m.Dfd
	}
	return 0
}

func (m *ProtobufFchownatEvent) GetFilename() []byte {
	if m != nil {
		return m.Filename
	}
	return nil
}

func (m *ProtobufFchownatEvent) GetUser() uint32 {
	if m != nil {
		return m.User
	}
	return 0
}

func (m *ProtobufFchownatEvent) GetGroup() uint32 {
	if m != nil {
		return m.Group
	}
	return 0
}

func (m *ProtobufFchownatEvent) GetFlag() int64 {
	if m != nil {
		return m.Flag
	}
	return 0
}

type ProtobufMkdirEvent struct {
	Pathname []byte `protobuf:"bytes,1,opt,name=pathname,proto3" json:"pathname,omitempty"`
	Mode     uint64 `protobuf:"varint,2,opt,name=mode" json:"mode,omitempty"`
}

func (m *ProtobufMkdirEvent) Reset()                    { *m = ProtobufMkdirEvent{} }
func (m *ProtobufMkdirEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtobufMkdirEvent) ProtoMessage()               {}
func (*ProtobufMkdirEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{10} }

func (m *ProtobufMkdirEvent) GetPathname() []byte {
	if m != nil {
		return m.Pathname
	}
	return nil
}

func (m *ProtobufMkdirEvent) GetMode() uint64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type ProtobufMkdiratEvent struct {
	Dfd      int64  `protobuf:"varint,1,opt,name=dfd" json:"dfd,omitempty"`
	Pathname []byte `protobuf:"bytes,2,opt,name=pathname,proto3" json:"pathname,omitempty"`
	Mode     uint64 `protobuf:"varint,3,opt,name=mode" json:"mode,omitempty"`
}

func (m *ProtobufMkdiratEvent) Reset()                    { *m = ProtobufMkdiratEvent{} }
func (m *ProtobufMkdiratEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtobufMkdiratEvent) ProtoMessage()               {}
func (*ProtobufMkdiratEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{11} }

func (m *ProtobufMkdiratEvent) GetDfd() int64 {
	if m != nil {
		return m.Dfd
	}
	return 0
}

func (m *ProtobufMkdiratEvent) GetPathname() []byte {
	if m != nil {
		return m.Pathname
	}
	return nil
}

func (m *ProtobufMkdiratEvent) GetMode() uint64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type ProtobufOpenEvent struct {
	Filename []byte `protobuf:"bytes,1,opt,name=filename,proto3" json:"filename,omitempty"`
	Flags    int64  `protobuf:"varint,2,opt,name=flags" json:"flags,omitempty"`
	Mode     uint64 `protobuf:"varint,3,opt,name=mode" json:"mode,omitempty"`
}

func (m *ProtobufOpenEvent) Reset()                    { *m = ProtobufOpenEvent{} }
func (m *ProtobufOpenEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtobufOpenEvent) ProtoMessage()               {}
func (*ProtobufOpenEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{12} }

func (m *ProtobufOpenEvent) GetFilename() []byte {
	if m != nil {
		return m.Filename
	}
	return nil
}

func (m *ProtobufOpenEvent) GetFlags() int64 {
	if m != nil {
		return m.Flags
	}
	return 0
}

func (m *ProtobufOpenEvent) GetMode() uint64 {
	if m != nil {
		return m.Mode
	}
	return 0
}

type ProtobufReadEvent struct {
	Fd    uint64 `protobuf:"varint,1,opt,name=fd" json:"fd,omitempty"`
	Buf   []byte `protobuf:"bytes,2,opt,name=buf,proto3" json:"buf,omitempty"`
	Count int64  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
}

func (m *ProtobufReadEvent) Reset()                    { *m = ProtobufReadEvent{} }
func (m *ProtobufReadEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtobufReadEvent) ProtoMessage()               {}
func (*ProtobufReadEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{13} }

func (m *ProtobufReadEvent) GetFd() uint64 {
	if m != nil {
		return m.Fd
	}
	return 0
}

func (m *ProtobufReadEvent) GetBuf() []byte {
	if m != nil {
		return m.Buf
	}
	return nil
}

func (m *ProtobufReadEvent) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type ProtobufWriteEvent struct {
	Fd    uint64 `protobuf:"varint,1,opt,name=fd" json:"fd,omitempty"`
	Buf   []byte `protobuf:"bytes,2,opt,name=buf,proto3" json:"buf,omitempty"`
	Count int64  `protobuf:"varint,3,opt,name=count" json:"count,omitempty"`
}

func (m *ProtobufWriteEvent) Reset()                    { *m = ProtobufWriteEvent{} }
func (m *ProtobufWriteEvent) String() string            { return proto.CompactTextString(m) }
func (*ProtobufWriteEvent) ProtoMessage()               {}
func (*ProtobufWriteEvent) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{14} }

func (m *ProtobufWriteEvent) GetFd() uint64 {
	if m != nil {
		return m.Fd
	}
	return 0
}

func (m *ProtobufWriteEvent) GetBuf() []byte {
	if m != nil {
		return m.Buf
	}
	return nil
}

func (m *ProtobufWriteEvent) GetCount() int64 {
	if m != nil {
		return m.Count
	}
	return 0
}

type Empty struct {
}

func (m *Empty) Reset()                    { *m = Empty{} }
func (m *Empty) String() string            { return proto.CompactTextString(m) }
func (*Empty) ProtoMessage()               {}
func (*Empty) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{15} }

type Metric struct {
	Count          uint64                  `protobuf:"varint,1,opt,name=Count,json=count" json:"Count,omitempty"`
	CommonEvent    *ProtobufCommonEvent    `protobuf:"bytes,2,opt,name=CommonEvent,json=commonEvent" json:"CommonEvent,omitempty"`
	ConnectV4Event *ProtobufConnectV4Event `protobuf:"bytes,3,opt,name=ConnectV4Event,json=connectV4Event" json:"ConnectV4Event,omitempty"`
	ConnectV6Event *ProtobufConnectV6Event `protobuf:"bytes,4,opt,name=ConnectV6Event,json=connectV6Event" json:"ConnectV6Event,omitempty"`
	ChmodEvent     *ProtobufChmodEvent     `protobuf:"bytes,5,opt,name=ChmodEvent,json=chmodEvent" json:"ChmodEvent,omitempty"`
	ChownEvent     *ProtobufChownEvent     `protobuf:"bytes,6,opt,name=ChownEvent,json=chownEvent" json:"ChownEvent,omitempty"`
	CloseEvent     *ProtobufCloseEvent     `protobuf:"bytes,7,opt,name=CloseEvent,json=closeEvent" json:"CloseEvent,omitempty"`
	FchmodEvent    *ProtobufFchmodEvent    `protobuf:"bytes,8,opt,name=FchmodEvent,json=fchmodEvent" json:"FchmodEvent,omitempty"`
	FchmodatEvent  *ProtobufFchmodatEvent  `protobuf:"bytes,9,opt,name=FchmodatEvent,json=fchmodatEvent" json:"FchmodatEvent,omitempty"`
	FchownEvent    *ProtobufFchownEvent    `protobuf:"bytes,10,opt,name=FchownEvent,json=fchownEvent" json:"FchownEvent,omitempty"`
	FchownatEvent  *ProtobufFchownatEvent  `protobuf:"bytes,11,opt,name=FchownatEvent,json=fchownatEvent" json:"FchownatEvent,omitempty"`
	MkdirEvent     *ProtobufMkdirEvent     `protobuf:"bytes,12,opt,name=MkdirEvent,json=mkdirEvent" json:"MkdirEvent,omitempty"`
	MkdiratEvent   *ProtobufMkdiratEvent   `protobuf:"bytes,13,opt,name=MkdiratEvent,json=mkdiratEvent" json:"MkdiratEvent,omitempty"`
	OpenEvent      *ProtobufOpenEvent      `protobuf:"bytes,14,opt,name=OpenEvent,json=openEvent" json:"OpenEvent,omitempty"`
	ReadEvent      *ProtobufReadEvent      `protobuf:"bytes,15,opt,name=ReadEvent,json=readEvent" json:"ReadEvent,omitempty"`
	WriteEvent     *ProtobufWriteEvent     `protobuf:"bytes,16,opt,name=WriteEvent,json=writeEvent" json:"WriteEvent,omitempty"`
}

func (m *Metric) Reset()                    { *m = Metric{} }
func (m *Metric) String() string            { return proto.CompactTextString(m) }
func (*Metric) ProtoMessage()               {}
func (*Metric) Descriptor() ([]byte, []int) { return fileDescriptor0, []int{16} }

func (m *Metric) GetCount() uint64 {
	if m != nil {
		return m.Count
	}
	return 0
}

func (m *Metric) GetCommonEvent() *ProtobufCommonEvent {
	if m != nil {
		return m.CommonEvent
	}
	return nil
}

func (m *Metric) GetConnectV4Event() *ProtobufConnectV4Event {
	if m != nil {
		return m.ConnectV4Event
	}
	return nil
}

func (m *Metric) GetConnectV6Event() *ProtobufConnectV6Event {
	if m != nil {
		return m.ConnectV6Event
	}
	return nil
}

func (m *Metric) GetChmodEvent() *ProtobufChmodEvent {
	if m != nil {
		return m.ChmodEvent
	}
	return nil
}

func (m *Metric) GetChownEvent() *ProtobufChownEvent {
	if m != nil {
		return m.ChownEvent
	}
	return nil
}

func (m *Metric) GetCloseEvent() *ProtobufCloseEvent {
	if m != nil {
		return m.CloseEvent
	}
	return nil
}

func (m *Metric) GetFchmodEvent() *ProtobufFchmodEvent {
	if m != nil {
		return m.FchmodEvent
	}
	return nil
}

func (m *Metric) GetFchmodatEvent() *ProtobufFchmodatEvent {
	if m != nil {
		return m.FchmodatEvent
	}
	return nil
}

func (m *Metric) GetFchownEvent() *ProtobufFchownEvent {
	if m != nil {
		return m.FchownEvent
	}
	return nil
}

func (m *Metric) GetFchownatEvent() *ProtobufFchownatEvent {
	if m != nil {
		return m.FchownatEvent
	}
	return nil
}

func (m *Metric) GetMkdirEvent() *ProtobufMkdirEvent {
	if m != nil {
		return m.MkdirEvent
	}
	return nil
}

func (m *Metric) GetMkdiratEvent() *ProtobufMkdiratEvent {
	if m != nil {
		return m.MkdiratEvent
	}
	return nil
}

func (m *Metric) GetOpenEvent() *ProtobufOpenEvent {
	if m != nil {
		return m.OpenEvent
	}
	return nil
}

func (m *Metric) GetReadEvent() *ProtobufReadEvent {
	if m != nil {
		return m.ReadEvent
	}
	return nil
}

func (m *Metric) GetWriteEvent() *ProtobufWriteEvent {
	if m != nil {
		return m.WriteEvent
	}
	return nil
}

func init() {
	proto.RegisterType((*ProtobufCommonEvent)(nil), "tracer.ProtobufCommonEvent")
	proto.RegisterType((*ProtobufConnectV4Event)(nil), "tracer.ProtobufConnectV4Event")
	proto.RegisterType((*ProtobufConnectV6Event)(nil), "tracer.ProtobufConnectV6Event")
	proto.RegisterType((*ProtobufChmodEvent)(nil), "tracer.ProtobufChmodEvent")
	proto.RegisterType((*ProtobufChownEvent)(nil), "tracer.ProtobufChownEvent")
	proto.RegisterType((*ProtobufCloseEvent)(nil), "tracer.ProtobufCloseEvent")
	proto.RegisterType((*ProtobufFchmodEvent)(nil), "tracer.ProtobufFchmodEvent")
	proto.RegisterType((*ProtobufFchmodatEvent)(nil), "tracer.ProtobufFchmodatEvent")
	proto.RegisterType((*ProtobufFchownEvent)(nil), "tracer.ProtobufFchownEvent")
	proto.RegisterType((*ProtobufFchownatEvent)(nil), "tracer.ProtobufFchownatEvent")
	proto.RegisterType((*ProtobufMkdirEvent)(nil), "tracer.ProtobufMkdirEvent")
	proto.RegisterType((*ProtobufMkdiratEvent)(nil), "tracer.ProtobufMkdiratEvent")
	proto.RegisterType((*ProtobufOpenEvent)(nil), "tracer.ProtobufOpenEvent")
	proto.RegisterType((*ProtobufReadEvent)(nil), "tracer.ProtobufReadEvent")
	proto.RegisterType((*ProtobufWriteEvent)(nil), "tracer.ProtobufWriteEvent")
	proto.RegisterType((*Empty)(nil), "tracer.Empty")
	proto.RegisterType((*Metric)(nil), "tracer.Metric")
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// Client API for MetricCollector service

type MetricCollectorClient interface {
	Process(ctx context.Context, opts ...grpc.CallOption) (MetricCollector_ProcessClient, error)
}

type metricCollectorClient struct {
	cc *grpc.ClientConn
}

func NewMetricCollectorClient(cc *grpc.ClientConn) MetricCollectorClient {
	return &metricCollectorClient{cc}
}

func (c *metricCollectorClient) Process(ctx context.Context, opts ...grpc.CallOption) (MetricCollector_ProcessClient, error) {
	stream, err := grpc.NewClientStream(ctx, &_MetricCollector_serviceDesc.Streams[0], c.cc, "/tracer.MetricCollector/Process", opts...)
	if err != nil {
		return nil, err
	}
	x := &metricCollectorProcessClient{stream}
	return x, nil
}

type MetricCollector_ProcessClient interface {
	Send(*Metric) error
	CloseAndRecv() (*Empty, error)
	grpc.ClientStream
}

type metricCollectorProcessClient struct {
	grpc.ClientStream
}

func (x *metricCollectorProcessClient) Send(m *Metric) error {
	return x.ClientStream.SendMsg(m)
}

func (x *metricCollectorProcessClient) CloseAndRecv() (*Empty, error) {
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	m := new(Empty)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// Server API for MetricCollector service

type MetricCollectorServer interface {
	Process(MetricCollector_ProcessServer) error
}

func RegisterMetricCollectorServer(s *grpc.Server, srv MetricCollectorServer) {
	s.RegisterService(&_MetricCollector_serviceDesc, srv)
}

func _MetricCollector_Process_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(MetricCollectorServer).Process(&metricCollectorProcessServer{stream})
}

type MetricCollector_ProcessServer interface {
	SendAndClose(*Empty) error
	Recv() (*Metric, error)
	grpc.ServerStream
}

type metricCollectorProcessServer struct {
	grpc.ServerStream
}

func (x *metricCollectorProcessServer) SendAndClose(m *Empty) error {
	return x.ServerStream.SendMsg(m)
}

func (x *metricCollectorProcessServer) Recv() (*Metric, error) {
	m := new(Metric)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var _MetricCollector_serviceDesc = grpc.ServiceDesc{
	ServiceName: "tracer.MetricCollector",
	HandlerType: (*MetricCollectorServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Process",
			Handler:       _MetricCollector_Process_Handler,
			ClientStreams: true,
		},
	},
	Metadata: "event-structs-generated.proto",
}

func init() { proto.RegisterFile("event-structs-generated.proto", fileDescriptor0) }

var fileDescriptor0 = []byte{
	// 800 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x56, 0x5d, 0x6f, 0xdb, 0x36,
	0x14, 0x9d, 0x2d, 0xd9, 0x8e, 0xae, 0x6c, 0xc7, 0xd3, 0xb2, 0x81, 0xcb, 0x92, 0x21, 0x30, 0xf6,
	0xe0, 0x87, 0x25, 0x0f, 0xde, 0x90, 0x60, 0x01, 0x82, 0x15, 0x70, 0x12, 0x14, 0x68, 0xf3, 0x01,
	0xa6, 0xe8, 0xd7, 0x9b, 0x22, 0x51, 0xb1, 0x51, 0x4b, 0x14, 0x28, 0xba, 0x41, 0x9f, 0xfa, 0x50,
	0xa0, 0xff, 0xb0, 0xff, 0xa7, 0x20, 0x69, 0x51, 0x54, 0x42, 0x07, 0x41, 0xdb, 0x37, 0xde, 0x8b,
	0x73, 0x0f, 0xcf, 0xbd, 0xba, 0x3c, 0x10, 0x6c, 0x93, 0xf7, 0x24, 0xe3, 0xbb, 0x05, 0x67, 0x8b,
	0x88, 0x17, 0xbb, 0x37, 0x24, 0x23, 0x2c, 0xe4, 0x24, 0xde, 0xcb, 0x19, 0xe5, 0x34, 0x68, 0x73,
	0x16, 0x46, 0x84, 0x0d, 0x3f, 0xc2, 0x2f, 0x97, 0x22, 0x71, 0xbd, 0x48, 0x26, 0x34, 0x4d, 0x69,
	0x76, 0x22, 0xca, 0x82, 0x2d, 0xf0, 0x5e, 0xcc, 0x52, 0x52, 0xf0, 0x30, 0xcd, 0x51, 0x63, 0xa7,
	0x31, 0x72, 0xb1, 0xc7, 0xcb, 0x44, 0x30, 0x00, 0xe7, 0x72, 0x16, 0xa3, 0xe6, 0x4e, 0x63, 0xe4,
	0x60, 0x27, 0x9f, 0xc5, 0x22, 0x83, 0x09, 0x47, 0x8e, 0xca, 0x30, 0xc2, 0x83, 0x00, 0xdc, 0xf3,
	0x30, 0x25, 0xc8, 0xdd, 0x69, 0x8c, 0x3c, 0xec, 0x66, 0x61, 0x4a, 0x44, 0xee, 0x69, 0x58, 0x4c,
	0x51, 0x4b, 0x12, 0xba, 0xd3, 0xb0, 0x98, 0x0e, 0x3f, 0x37, 0xe0, 0xb7, 0x4a, 0x41, 0x96, 0x91,
	0x88, 0xbf, 0xfc, 0x57, 0x89, 0xd8, 0x80, 0xd6, 0x55, 0x18, 0xc7, 0x4c, 0x0a, 0xe8, 0xe1, 0x56,
	0x21, 0x02, 0x91, 0x3d, 0x96, 0xd9, 0xa6, 0xca, 0xc6, 0x65, 0xf6, 0x2a, 0xa7, 0x4c, 0x49, 0x10,
	0x58, 0x11, 0x48, 0xac, 0xcc, 0xba, 0x4b, 0x6c, 0x99, 0x3d, 0x27, 0x3c, 0x2b, 0xa4, 0x8e, 0x1e,
	0x6e, 0x65, 0x22, 0xb0, 0x0a, 0xd9, 0xb7, 0x08, 0xf1, 0xac, 0x42, 0xbc, 0x1f, 0x27, 0xe4, 0x18,
	0x02, 0xad, 0x63, 0x9a, 0xd2, 0x58, 0x69, 0xd8, 0x84, 0xb5, 0x64, 0x36, 0x27, 0x62, 0x8e, 0x52,
	0x46, 0x17, 0xeb, 0x58, 0xcc, 0x35, 0xa5, 0x31, 0x91, 0x42, 0x5c, 0x2c, 0xcf, 0xc3, 0xb7, 0x26,
	0x0b, 0xbd, 0xcd, 0x1e, 0xc5, 0xb2, 0x28, 0x48, 0x39, 0x57, 0x79, 0x16, 0x0a, 0x6f, 0x18, 0x5d,
	0xe4, 0x65, 0x37, 0x32, 0x18, 0xfe, 0x65, 0x70, 0xcf, 0x69, 0x41, 0x14, 0x77, 0x1f, 0x9a, 0x49,
	0xbc, 0x5c, 0x96, 0x66, 0x12, 0x0f, 0xff, 0xab, 0x56, 0xeb, 0x34, 0xaa, 0x1a, 0xb9, 0x03, 0xb3,
	0x8a, 0x7f, 0x03, 0xbf, 0xd6, 0x4b, 0x43, 0xae, 0x8a, 0x07, 0xe0, 0xc4, 0xcb, 0x6a, 0x07, 0x8b,
	0x63, 0xad, 0xa3, 0xe6, 0x8a, 0xb9, 0x38, 0x06, 0xf5, 0x45, 0x4d, 0x95, 0x1e, 0x8c, 0x45, 0xd5,
	0x23, 0x87, 0xf1, 0xa9, 0x51, 0x13, 0x4b, 0x6f, 0xb3, 0x6f, 0x16, 0x2b, 0x6f, 0x74, 0x6c, 0x37,
	0xba, 0xc6, 0x8d, 0x02, 0x99, 0xcc, 0xc3, 0x1b, 0xb9, 0x35, 0x0e, 0x96, 0x67, 0x73, 0x69, 0xce,
	0xde, 0xc5, 0x33, 0xa6, 0x3f, 0x77, 0x1e, 0xf2, 0xa9, 0xf9, 0xb9, 0xcb, 0xd8, 0x3a, 0xf7, 0xd7,
	0xb0, 0x51, 0x63, 0x79, 0xb0, 0x13, 0xcd, 0xdc, 0x5c, 0xc1, 0xec, 0xd4, 0xbe, 0xe8, 0xcf, 0x25,
	0xf3, 0x45, 0x4e, 0x1e, 0xb1, 0x8d, 0x1b, 0xd0, 0x12, 0x8d, 0x15, 0x4b, 0x97, 0x51, 0x81, 0x95,
	0xfa, 0x59, 0x45, 0x8d, 0x49, 0xb8, 0x62, 0xcb, 0x06, 0xe0, 0x5c, 0x2f, 0x92, 0xa5, 0x54, 0x71,
	0x14, 0x17, 0x44, 0x74, 0x91, 0x95, 0xa6, 0xa5, 0x82, 0xe1, 0xf3, 0x6a, 0x8e, 0xaf, 0xd8, 0x8c,
	0x93, 0xef, 0x63, 0xeb, 0x40, 0xeb, 0x24, 0xcd, 0xf9, 0x87, 0xe1, 0x97, 0x0e, 0xb4, 0xcf, 0x08,
	0x67, 0xb3, 0x48, 0x20, 0x27, 0x12, 0xa9, 0xe8, 0x14, 0x32, 0x38, 0x02, 0xdf, 0xf0, 0x5f, 0xc9,
	0xec, 0x8f, 0xff, 0xd8, 0x53, 0x2e, 0xbd, 0x67, 0xb1, 0x68, 0xec, 0x47, 0x86, 0x5f, 0x9f, 0x42,
	0xbf, 0x6e, 0x9e, 0x52, 0x87, 0x3f, 0xfe, 0xf3, 0x3e, 0x83, 0x89, 0xc2, 0xfd, 0xa8, 0x6e, 0xb9,
	0x06, 0x8f, 0xf2, 0x3e, 0xb9, 0x79, 0x0f, 0xf0, 0xec, 0xdf, 0xe1, 0x59, 0x3a, 0xe6, 0x21, 0x40,
	0xe5, 0x5d, 0x72, 0x51, 0xfd, 0xf1, 0xe6, 0x3d, 0x0e, 0x8d, 0xc0, 0x60, 0x18, 0x84, 0xac, 0x2d,
	0x1f, 0x26, 0x6a, 0xaf, 0xaa, 0x2d, 0x11, 0xa2, 0x56, 0x3f, 0x63, 0x51, 0xab, 0x1d, 0x09, 0x75,
	0x56, 0xd4, 0x6a, 0x04, 0x86, 0xa8, 0xf2, 0xaf, 0x23, 0xf0, 0x0d, 0x9f, 0x42, 0x6b, 0xf6, 0x4f,
	0x60, 0x40, 0xb0, 0x9f, 0x18, 0xb2, 0x27, 0xd0, 0xab, 0x79, 0x15, 0xf2, 0x24, 0xc1, 0xb6, 0x9d,
	0x60, 0x09, 0xc2, 0xbd, 0xa4, 0xe6, 0x6f, 0x4a, 0x83, 0x6e, 0x1e, 0x56, 0x6a, 0xd0, 0xdd, 0x0b,
	0x0d, 0xba, 0x7d, 0xa5, 0xa1, 0xb2, 0x20, 0xe4, 0xaf, 0xd4, 0x50, 0x81, 0xa4, 0x06, 0xc3, 0xb6,
	0x0e, 0x01, 0x2a, 0x0b, 0x41, 0x5d, 0xfb, 0x0c, 0x2b, 0x04, 0x86, 0xb4, 0x32, 0x9c, 0x27, 0xd0,
	0x35, 0x8d, 0x03, 0xf5, 0x64, 0xf5, 0x96, 0xb5, 0xba, 0xbc, 0xbe, 0x9b, 0x9a, 0x56, 0x73, 0x00,
	0x9e, 0x36, 0x08, 0xd4, 0x97, 0xe5, 0xbf, 0xdf, 0x2d, 0xd7, 0x00, 0xec, 0x51, 0x6d, 0x26, 0x07,
	0xe0, 0xe9, 0xe7, 0x8f, 0xd6, 0xed, 0x85, 0x1a, 0x80, 0x3d, 0xa6, 0xad, 0xe2, 0x10, 0xa0, 0x7a,
	0xea, 0x68, 0x60, 0xef, 0xb7, 0x42, 0x60, 0xb8, 0xd5, 0xe7, 0xf1, 0xff, 0xb0, 0xae, 0x9e, 0xf5,
	0x84, 0xce, 0xe7, 0x24, 0xe2, 0x94, 0x05, 0x7f, 0x43, 0xe7, 0x92, 0xd1, 0x88, 0x14, 0x45, 0xd0,
	0x2f, 0x59, 0x14, 0x66, 0xb3, 0x57, 0xc6, 0xca, 0x14, 0x7e, 0x1a, 0x35, 0xae, 0xdb, 0xf2, 0x77,
	0xec, 0x9f, 0xaf, 0x01, 0x00, 0x00, 0xff, 0xff, 0x6e, 0x54, 0x33, 0x07, 0xaf, 0x09, 0x00, 0x00,
}
